services:

  postgres:
    image: postgres:18.1
    restart: no
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SUPERUSER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
